"""Fachada pública Logistics."""

from app.logistics.commands import (
    add_shipment_item,
    add_shipment_package,
    add_shipment_packages_batch,
    add_shipment_reference,
    advance_shipment_status,
    annul_planned_shipment,
    create_logistics_provider,
    create_shipment,
    delete_shipment,
    remove_shipment_item,
    remove_shipment_package,
    remove_shipment_reference,
    set_package_contents,
    update_logistics_provider,
    update_shipment,
    update_shipment_item,
    update_shipment_package,
    update_shipment_packages_batch,
    upsert_document_summary,
)
from app.logistics.errors import LogisticsError
from app.logistics.models import (
    PROVIDER_TYPES,
    SHIPMENT_MODALS,
    SHIPMENT_PROVIDER_TYPES,
)
from app.logistics.queries import (
    allocation_bases,
    declared_totals_by_document,
    find_shipments_by_reference,
    get_logistics_provider,
    get_shipment,
    get_shipment_by_code,
    list_logistics_providers,
    list_shipments,
    order_item_candidates,
    physical_divergences,
    physical_totals_derived,
    residuals_for_order,
    shipped_qty_by_order_item,
    shipment_item_facts,
)

__all__ = [
    "LogisticsError",
    "SHIPMENT_MODALS",
    "PROVIDER_TYPES",
    "SHIPMENT_PROVIDER_TYPES",
    "create_logistics_provider",
    "update_logistics_provider",
    "get_logistics_provider",
    "list_logistics_providers",
    "create_shipment",
    "update_shipment",
    "advance_shipment_status",
    "add_shipment_item",
    "update_shipment_item",
    "remove_shipment_item",
    "add_shipment_package",
    "add_shipment_packages_batch",
    "update_shipment_package",
    "update_shipment_packages_batch",
    "remove_shipment_package",
    "set_package_contents",
    "add_shipment_reference",
    "remove_shipment_reference",
    "upsert_document_summary",
    "delete_shipment",
    "annul_planned_shipment",
    "get_shipment",
    "get_shipment_by_code",
    "list_shipments",
    "find_shipments_by_reference",
    "shipped_qty_by_order_item",
    "shipment_item_facts",
    "residuals_for_order",
    "physical_totals_derived",
    "declared_totals_by_document",
    "physical_divergences",
    "allocation_bases",
    "order_item_candidates",
]
